### ISSUE TITLE
Failed to install plugin "AnyBlock"

### ISSUE THREAD

**Issue by Antalis** [LincZero/obsidian-any-block#39]
Hello,

Obsidian version : 1.6.7

I tried to install the "Any Block" plugin but I got an error: "Failed to install plugin "AnyBlock"" 
Strangely, the proposed version of the Any Block plugin is in version 3.0.0 (in Obsidian), but on github, the latest is 2.2.0

On dev console : 
```
app.js:1 Error: Request failed, status 404
    at new t (app.js:1:2030716)
    at vK (app.js:1:2030908)
    at app.js:1:2031587
    at app.js:1:237138
    at Object.next (app.js:1:237243)
    at a (app.js:1:235961)
```

With Logstravaganza plugin :
```
time: 2024-07-31T14:21:16.170Z
from: app.js:1:2299726
level: error
{
  "status": 404,
  "headers": {
    "cache-control": "no-cache",
    "content-encoding": "gzip",
    "content-length": "41",
    "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
    "content-type": "application/json; charset=utf-8",
    "date": "Wed, 31 Jul 2024 14:21:16 GMT",
    "referrer-policy": "no-referrer-when-downgrade",
    "server": "GitHub.com",
    "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
    "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
    "x-content-type-options": "nosniff",
    "x-github-request-id": "1ACA:0EAF:335D194:343BE0E:66AA485B",
    "x-xss-protection": "0"
  }
}
```

**Comment by LincZero** [comment]
I temporarily rolled back the version of the community plugin, thinking that I would need to actively commit to update the plugin. I'm very sorry to trouble you.

**Comment by LincZero** [comment]
6cf835ff84794df424f0a153e03536cd3888881e

**Comment by Antalis** [comment]
Ok, thank you, problem solved and quickly :-)
Thank you for everything.
